//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria
    {
        public int id { get; set; }
        public string accion { get; set; }
        public System.DateTime fecha { get; set; }
        public string tabla { get; set; }
        public string modificadoPor { get; set; }
        public Nullable<int> idUsuarios { get; set; }
        public Nullable<int> idPadres { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual padres padres { get; set; }
    }
}
