//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletaRetiro
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombrePadre { get; set; }
        public string cedulaPadre { get; set; }
        public string nombreEstudiante { get; set; }
        public string seccionEstudiante { get; set; }
        public string retiroLecciones { get; set; }
        public string justificarRetiro { get; set; }
        public string firma { get; set; }
        public string recibidoPor { get; set; }
        public byte[] sello { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public int idConsecutivo { get; set; }
    
        public virtual retiroConsecutivo retiroConsecutivo { get; set; }
    }
}
