//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace controlAdministrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisoComprobante
    {
        public int id { get; set; }
        public bool presentaComprabante { get; set; }
        public bool multaSalario { get; set; }
        public string tipoComprobante { get; set; }
        public string otroComprobante { get; set; }
        public string aprobadoPor { get; set; }
        public string firmadoPor { get; set; }
        public byte[] sello { get; set; }
        public int idPermiso { get; set; }
    
        public virtual boletaPermiso boletaPermiso { get; set; }
    }
}
